name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1.3

      - name: Restore NuGet packages
        run: msbuild CarService.sln -t:restore -p:RestorePackagesConfig=true

      - name: Build
        run: msbuild CarService.sln -p:Configuration=Release -m

      - name: Test
        run: vstest.console.exe UserRegistration.Tests\bin\Release\UserRegistration.Tests.dll

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: CarService
          path: |
            CarService/bin/Release/*.exe
            CarService/bin/Release/*.dll
            CarService/bin/Release/*.config
